### ISSUE TITLE
Access from remote location?

### ISSUE THREAD

**Issue by osnard** [unoconv/unoserver-docker#37]
This is more like a question. Unfortunately I was not really able to figure this out by the documentation I found.

Is is possible to access this server from a remote location using some kind of client application?

Apparently a server is started (https://github.com/unoconv/unoserver-docker/blob/main/build-context/supervisor/config/entrypoint.sh#L21) but it looks like this image was meant for "interactive" mode only (https://github.com/unoconv/unoserver-docker/blob/main/build-context/supervisor/config/entrypoint.sh#L31-L35).

I was wondering if one could have this image running as a persistent service and than just call it using a client (maybe even a HTTP REST interface)?

**Comment by jimisola** [comment]
It is meant to be interactive. Either from within the container or from to outside.

There is no functionality to call it using for example a REST API. You could probably run unoserver directly but I can't recall what API it has for clients.

**Comment by benglewis** [comment]
@osnard You can use my image instead:
https://github.com/benglewis/unoserver-docker/tree/main
It is designed to be used in Kubernetes as a secondary container alongside a primary container that runs a Python service with the `unoserver-client` and connects to it. That way you can use `unoserver` via a server instead of from a CLI.

**Comment by jimisola** [comment]
@benglewis It would be nice to have two container images with the same name but different use cases.


1. Would you be able to provide a PR for your?

2. I haven't looked at your solution. Is it possible to combine the two use cases into one image or does it have to be two?

**Comment by jimisola** [comment]
@benglewis I had a look at your fork now. By removing the superuser you changed the functionality completely but you've kept the name the same - which probably will cause confusion for users since you haven't even updated the README.md file.

It's great that you solved a use-case but did you consider the above? And was there a way that we could have kept both use-cases under the unoconv namespace?

Lastly, I'm curious on why you had to create different images for linux/amd64 and darwin/arm64.

**Comment by benglewis** [comment]
@jimisola I can change the README. I was looking for a fast solution hence why I did it in my own way.

It is possible to create a single image, but it would involve layers copying the supervisor code and then other layers deleting them (not ideal).
Alternatively, we could just have two different `Dockerfile`'s indeed. Do you want me to try to open a PR that does this? Would you be happy to support an image which is designed for use as a server? I thought that this repo intentionally only targeting CLIs, so I used it as a base and created my own thing to avoid putting it here and people coming to you with maintenance questions on the server approach.

Regarding the multi-platform: I just wanted to have the ability to build a `linux/arm64` image to run on my Mac without having to use any Rosetta translation of CPU commands, which should be possible, but I encountered issues and chose to defer this for now.

**Comment by jimisola** [comment]
@benglewis Ok. I think I tried out platform using QEMU before but also ran into issues. 

I agree. My idea was also having two different Dockerfile's. Ideally, I'd like to have them in same repo.

See: https://github.com/docker/build-push-action/discussions/1034

Might need to have two different workflows and I also need to figure out how to add a suffix (-cli, -server) to the image.

You can configure the `imageid` (https://github.com/docker/build-push-action?tab=readme-ov-file#outputs) but the workflow uses[ docker/metadata action](https://github.com/docker/metadata-action), so it's deferred there.

**Comment by jimisola** [comment]
I think that this might work:

```github
name: Publish Docker Images to GHCR

on:
  push:
    branches:
      - main
    tags: 
      - "v*.*.*"
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-n-publish-cli:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Login to image registry ${{ env.REGISTRY }}
        if: github.ref_type == 'tag'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for CLI
        id: meta-cli
        uses: docker/metadata-action@9dc751fe249ad99385a2583ee0d084c400eee04e
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-cli
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image for CLI
        id: build-and-push-cli
        uses: docker/build-push-action@v5
        with:
          context: ./cli
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta-cli.outputs.tags }}
          labels: ${{ steps.meta-cli.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-n-publish-server:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Login to image registry ${{ env.REGISTRY }}
        if: github.ref_type == 'tag'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for Server
        id: meta-server
        uses: docker/metadata-action@9dc751fe249ad99385a2583ee0d084c400eee04e
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-server
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image for Server
        id: build-and-push-server
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

**Comment by jimisola** [comment]
It would have been nice if no image is published unless both are built but I'm not sure yet on how to accomplish that.

Oh, I forgot to answer your question. Please do open a PR. I'll be glad to accept a working one.

Since this is the subproject to the main unoconv I think it's good to "officially" support the two container images (cli and server). When we have them working there are a lot of similarities anyway, e.g. upgrading to new alpine versions and make sure that nothing is broken... ;)

**Comment by jimisola** [comment]
@benglewis Are you still interested in providing a PR?

**Comment by dulacp** [comment]
> It would have been nice if no image is published unless both are built but I'm not sure yet on how to accomplish that.

I think you can get inspired by [this workflow layout](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners) where a `merge` job needs the `build` job to complete.

@benglewis, if you don't have time I can work on that PR with pleasure.

Cheers

**Comment by benglewis** [comment]
> > It would have been nice if no image is published unless both are built but I'm not sure yet on how to accomplish that.
> 
> I think you can get inspired by [this workflow layout](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners) where a `merge` job needs the `build` job to complete.
> 
> @benglewis, if you don't have time I can work on that PR with pleasure.
> 
> Cheers

Hi @dulacp,

Yes; I no longer work at the same employer for whom I wrote these changes, so I would appreciate the help

**Comment by jimisola** [comment]
@dulacp @benglewis Haven't been able to respond earlier. And sadly, the container suddenly doesn't work on my private Ubuntu for some reason. It simply hangs, but it works on my Ubuntu work computer, so I have to look into that as well.

Just so sort out the use-cases:


1. as interactive (using -it) and can convert either directly from `docker run` command or when interactive in the container
2. as a server listening on port 2002 for XMLRPC calls

I think we can combine the two use-cases in one-container if it's documented properly.

For use-case 2 my suggested solution is that instead of outputting that the container has started in a non-interactive mode we use another supervisor.d conf to start unoserver and have it listen on port 2003.

The container would be backward compatible then, i.e. no breaking changes.

For

* use case 1: `docker run -it...`
* use case 2: `docker run ...`

How does that sound?

**Comment by jimisola** [comment]
I have a new container that I think work but I'm not able to test it because I can't access the ports from the host machine.

Starting with: `docker run -p 2002:2002 -p 2003:2003 `

But, get "ConnectionResetError: [Errno 104] Connection reset by peer" when using

`unoconvert --host-location remote example.docx example.pdf`

**Comment by jimisola** [comment]
@osnard I believe I have implemented your feature request now while maintaining backwards compatibility.

I've tested but could you please try and build it locally to confirm that this is what you requested before I release?

branch: https://github.com/unoconv/unoserver-docker/tree/feature/add_run_as_server

**Comment by jimisola** [comment]
I just release v0.3.0 with this feature, see README for more information.
